opit_opit_hrm_core:
    pager:
        max_results: %max_results%
        max_pages: %max_pages%
    mailing:
        mail_sender: %mail_sender%
    currency:
        default_currency:   %default_currency%
        currency_format:
            decimals:       2
            dec_point:      ','
            thousands_sep:  ' '
        mid_rate:
            day: 15
            modifier: '-1 month'