imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@OpitNotesCoreBundle/Resources/config/config.yml" }
    - { resource: "@OpitNotesUserBundle/Resources/config/config.yml" }
    - { resource: "@OpitNotesTravelBundle/Resources/config/config.yml" }
    - { resource: "@OpitNotesCurrencyRateBundle/Resources/config/config.yml" }
    - { resource: "@OpitNotesLeaveBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        api: auto
    templating:
        engines: ['twig']
        assets_version: %version_number%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        version_number: %version_number%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ OpitNotesCoreBundle, OpitNotesUserBundle, OpitNotesTravelBundle, OpitNotesLeaveBundle, OpitNotesHiringBundle ]
    #java: /usr/bin/java
    filters:
        coffee:
            bin: /usr/bin/coffee
            node: /usr/bin/nodejs
            apply_to: "\.coffee$"
        sass:
            bin: /usr/local/bin/sass
            apply_to: "\.scss$"
            load_paths: [ "%kernel.root_dir%/Resources/public/css" ]
        cssrewrite: ~
        #closure:
            #jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: Opit\Notes\UserBundle\Entity\User
            Opit\Notes\TravelBundle\Model\TravelRequestUserInterface: Opit\Notes\UserBundle\Entity\User
            Opit\Notes\TravelBundle\Model\TravelStatusInterface: Opit\Notes\StatusBundle\Entity\Status
            Opit\Notes\TravelBundle\Model\TravelCurrencyInterface: Opit\Notes\CurrencyRateBundle\Entity\Currency
            Opit\Notes\NotificationBundle\Model\NotificationUserInterface: Opit\Notes\UserBundle\Entity\User
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
                
# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    port:       %mailer_port%
    username:   %mailer_user%
    password:   %mailer_password%
    encryption: %mailer_encryption%

fos_js_routing:
    routes_to_expose: [ OpitNotesUserBundle_\w+, OpitNotesTravelBundle_\w+, OpitNotesCurrencyRateBundle_\w+, OpitNotesLeaveBundle_\w+, OpitNotesHiringBundle_\w+ ]
    
# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            softdeleteable: true
            timestampable: true
            blameable:     true

# Sensio Extra Configuration
sensio_framework_extra:
    # For the Rest API the view annotations should be disabled
    # in order to the FOSRestBundle is able to use the view annotations.
    # @Template() annotations will be delegated by the fos_rest response listener.
    #
    # @see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/3-listener-support.md
    view: { annotations: false }

# Rest API Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: force
        formats:
            json:   true
            xml:    true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json, xml ], prefer_extension: false }