fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

OpitOpitHrmCoreBundle:
    resource: "@OpitOpitHrmCoreBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_user:
    resource: "@OpitOpitHrmUserBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_notification:
    resource: "@OpitOpitHrmNotificationBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_status:
    resource: "@OpitOpitHrmStatusBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_leave:
    resource: "@OpitOpitHrmLeaveBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_currency_rate:
    resource: "@OpitOpitHrmCurrencyRateBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_travel:
    resource: "@OpitOpitHrmTravelBundle/Controller/"
    type:     annotation
    prefix:   /

opit_opithrm_hiring:
    resource: "@OpitOpitHrmHiringBundle/Controller/"
    type:     annotation
    prefix:   /

