opit_notes_leave:
    resource: "@OpitNotesLeaveBundle/Controller/"
    type:     annotation
    prefix:   /

opit_notes_currency_rate:
    resource: "@OpitNotesCurrencyRateBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

opit_notes_travel:
    resource: "@OpitNotesTravelBundle/Controller/"
    type:     annotation
    prefix:   /

opit_notes_user:
    resource: "@OpitNotesUserBundle/Controller/"
    type:     annotation
    prefix:   /

