security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Opit\Notes\UserBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1
        Opit\Notes\TravelBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1

    role_hierarchy:
        ROLE_USER: ~
        ROLE_TEAM_MANAGER: ROLE_USER
        ROLE_GENERAL_MANAGER: [ROLE_TEAM_MANAGER, ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_TEAM_MANAGER, ROLE_GENERAL_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_TEAM_MANAGER, ROLE_GENERAL_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        administrators:
            entity: { class: OpitNotesUserBundle:User }                    

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/secured/login$
            security: false

        secured_area:
            pattern:    ^/secured/
            simple_form:
                authenticator: ldap
                check_path: OpitNotesUserBundle_check
                login_path: OpitNotesUserBundle_security_login
                default_target_path: OpitNotesUserBundle_user_show_infoboard
            logout:
                path:   OpitNotesUserBundle_logout
                target: OpitNotesUserBundle_security_login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/secured, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    acl:
        connection: default