security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Opit\OpitHrm\UserBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1
        Opit\OpitHrm\TravelBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1
        Opit\OpitHrm\LeaveBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1
        Opit\OpitHrm\HiringBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1
        Opit\OpitHrm\HiringBundle\Entity\JobPosition:
            algorithm:        sha512
            iterations:       1

    role_hierarchy:
        ROLE_CUSTOMER: ~
        ROLE_USER: ROLE_CUSTOMER
        ROLE_PAYROLL: ROLE_CUSTOMER
        ROLE_STAKEHOLDER: ROLE_CUSTOMER
        ROLE_FINANCE: ROLE_CUSTOMER
        ROLE_TEAM_MANAGER: ROLE_USER
        ROLE_GENERAL_MANAGER: ROLE_TEAM_MANAGER
        ROLE_SYSTEM_ADMIN: [ROLE_CUSTOMER, ROLE_PAYROLL, ROLE_STAKEHOLDER, ROLE_FINANCE, ROLE_USER]
        ROLE_ADMIN:       [ROLE_GENERAL_MANAGER, ROLE_SYSTEM_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    opit:  { password: opit }
        administrators:
            entity: { class: OpitOpitHrmUserBundle:User }                    

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/secured/
            provider: administrators
            anonymous: ~
            simple_form:
                authenticator: ldap
                check_path: OpitOpitHrmUserBundle_check
                login_path: OpitOpitHrmUserBundle_security_login
                default_target_path: OpitOpitHrmUserBundle_user_show_infoboard
            logout:
                path:   OpitOpitHrmUserBundle_logout
                target: OpitOpitHrmUserBundle_security_login

        customer:
            pattern: ^/customer/
            http_basic:
                realm: "Secured Customer Area"
            provider: administrators

        feeds:
            pattern: ^/feeds/
            http_basic:
                realm: "Secured Feed Area"
            provider: in_memory

    access_control:
        - { path: ^/secured/(login|login_check|logout)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured, roles: ROLE_USER }
        - { path: ^/customer, roles: ROLE_CUSTOMER }

    acl:
        connection: default

    access_decision_manager:
        strategy: unanimous
