security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Opit\Notes\UserBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1
        Opit\Notes\TravelBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1
        Opit\Notes\LeaveBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1
        Opit\Notes\HiringBundle\Entity\Token:
            algorithm:        sha512
            iterations:       1
        Opit\Notes\HiringBundle\Entity\JobPosition:
            algorithm:        sha512
            iterations:       1

    role_hierarchy:
        ROLE_CUSTOMER: ~
        ROLE_USER: ROLE_CUSTOMER
        ROLE_PAYROLL: ROLE_CUSTOMER
        ROLE_TEAM_MANAGER: ROLE_USER
        ROLE_GENERAL_MANAGER: ROLE_TEAM_MANAGER
        ROLE_SYSTEM_ADMIN: ROLE_USER
        ROLE_ADMIN:       [ROLE_GENERAL_MANAGER, ROLE_SYSTEM_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    opit:  { password: opit }
        administrators:
            entity: { class: OpitNotesUserBundle:User }                    

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/secured/login$
            security: false

        secured_area:
            pattern:    ^/secured/
            provider: administrators
            simple_form:
                authenticator: ldap
                check_path: OpitNotesUserBundle_check
                login_path: OpitNotesUserBundle_security_login
                default_target_path: OpitNotesUserBundle_user_show_infoboard
            logout:
                path:   OpitNotesUserBundle_logout
                target: OpitNotesUserBundle_security_login

        customer:
            pattern: ^/customer/
            http_basic:
                realm: "Secured Customer Area"

        feeds:
            pattern: ^/feeds/
            http_basic:
                realm: "Secured Feed Area"
            provider: in_memory

    access_control:
        - { path: ^/secured, roles: ROLE_USER }
        - { path: ^/customer, roles: ROLE_CUSTOMER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    acl:
        connection: default