parameters:
    notes_user_status:
        1: Active
        0: Inactive

opit_notes_user:
    min_php_version: 5.4.0
    ldap:
        enabled: false
        host: %ldap_host%
        accountDomainNameShort: %ldap_domain_name_short%
        baseDn: %ldap_base_dn%